spring:
  application:
    name: delivery-fee-calculator

  datasource:
    url: jdbc:h2:mem:delivery_fee_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

app:
  weather:
    api:
      url: https://www.ilmateenistus.ee/ilma_andmed/xml/observations.php
    import-config:
      cron: "0 15 * * * *"
    stations:
      tallinn:
        name: Tallinn-Harku
        wmo-code: "26038"
      tartu:
        name: Tartu-Tõravere
        wmo-code: "26242"
      parnu:
        name: Pärnu
        wmo-code: "41803"

springdoc:
  api-docs:
    version: openapi_3_1
